spring.application.name=activity3_2
server.port=8082
server.servlet.context-path=/activity3_2
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/xfile/,classpath:/yfile/
